extern void cn_InitCommands();
extern void cn_Cmd_LoadScript(unsigned char * Ptr);
extern void cn_Cmd_SetUCode(unsigned char * Ptr);
extern void cn_Cmd_LoadFile(unsigned char * Ptr);
extern void cn_Cmd_ClearSegment(unsigned char * Ptr);
extern void cn_Cmd_LoadRAM(unsigned char * Ptr);
extern void cn_Cmd_FindDLists(unsigned char * Ptr);
extern void cn_Cmd_AddDList(unsigned char * Ptr);
extern void cn_Cmd_ClearDLists(unsigned char * Ptr);
extern void cn_Cmd_SetScale(unsigned char * Ptr);
extern void cn_cmd_SegmentUsage(unsigned char * Ptr);
extern void cn_Cmd_About(unsigned char * Ptr);
