#define IDC_MAIN_OPENGL				101
#define IDC_MAIN_STATUSBAR			102

#define IDM_MAINMENU				200

#define IDM_FILE_OPEN				201
#define IDM_FILE_SAVE				202
#define IDM_FILE_EXIT				203

#define IDM_CAMERA_RESETCOORDS		211

#define IDM_MAP_PREVDLIST			221
#define IDM_MAP_NEXTDLIST			222
#define IDM_MAP_PREVHEADER			223
#define IDM_MAP_NEXTHEADER			224

#define IDM_SCENE_PREVHEADER		231
#define IDM_SCENE_NEXTHEADER		232

#define IDM_ACTORS_MAPRENDER		241
#define IDM_ACTORS_SELECTPREV		242
#define IDM_ACTORS_SELECTNEXT		243
#define IDM_ACTORS_JUMPFIRST		244
#define IDM_ACTORS_JUMPLAST			245
#define IDM_ACTORS_SCENERENDER		246
#define IDM_ACTORS_SCENEPREV		247
#define IDM_ACTORS_SCENENEXT		248

#define IDM_OPTIONS_FILTERNEAREST	251
#define IDM_OPTIONS_FILTERLINEAR	252
#define IDM_OPTIONS_FILTERMIPMAP	253
#define IDM_OPTIONS_MULTITEXTURE	254

#define IDM_HELP_ABOUT				261
