#define IDC_MAIN_OPENGL				101
#define IDC_MAIN_STATUSBAR			102

#define IDM_MAINMENU				200

#define IDM_FILE_OPEN				201
#define IDM_FILE_SAVE				202
#define IDM_FILE_EXIT				203

#define IDM_LEVEL_PREVLEVEL			211
#define IDM_LEVEL_NEXTLEVEL			212

#define IDM_SCENE_PREVHEADER		221
#define IDM_SCENE_NEXTHEADER		222
#define IDM_MAP_PREVHEADER			223
#define IDM_MAP_NEXTHEADER			224

#define IDM_ACTORS_MAPRENDER		231
#define IDM_ACTORS_SELECTPREV		232
#define IDM_ACTORS_SELECTNEXT		233
#define IDM_ACTORS_JUMPFIRST		234
#define IDM_ACTORS_JUMPLAST			235
#define IDM_ACTORS_SCENERENDER		236
#define IDM_ACTORS_SCENEPREV		237
#define IDM_ACTORS_SCENENEXT		238

#define IDM_OPTIONS_RESETCAMCOORDS	241
#define IDM_OPTIONS_FILTERNEAREST	242
#define IDM_OPTIONS_FILTERLINEAR	243
#define IDM_OPTIONS_FILTERMIPMAP	244
#define IDM_OPTIONS_MULTITEXTURE	245

#define IDM_HELP_ABOUT				251
